name: dast-scan-action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  kics-job:
    runs-on: ubuntu-latest
    name: dast-action
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Scan Iac with kics
    - name: run kics Scan
      uses: Checkmarx/dast-github-action@v1.0.0-beta
      with:
        command: "web"
        config: 'security_tweets.yaml'
        base_url: "http://testhtml5.vulnweb.com"
        environment_id: "f4b85c89-a720-4c21-8379-8a9535e98fde"
        #fail_on: "HIGH"
        verbose: true
